name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
  
    - name: Build Backend
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        context: log-app/
        image: log-app
        tags: latest ${{ github.sha }}
        containerfiles: ./log-app/Dockerfile

    - name: Push to Github Packages
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
